# Generated by Django 3.0.9 on 2020-08-30 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which object was last modified.', verbose_name='modified at')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='clothes/pictures/', verbose_name='Clothes main picture')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='clothes/pictures/', verbose_name='Second clothe picture')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='clothes/pictures/', verbose_name='Three clothe picture')),
                ('clothe_images', models.PositiveSmallIntegerField(default=0, help_text='The limits per clothes are 2 images. Excluding the main.', validators=[django.core.validators.MaxValueValidator(limit_value=2)], verbose_name='Clothe pictures related')),
                ('description', models.TextField(blank=True, help_text='User can add a description with 500 charters.', max_length=500, verbose_name='Clothe description')),
                ('size', models.CharField(choices=[('XS', 'Extra Short'), ('S', 'Short'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Super Extra Large'), ('XXXL', 'Super Super Extra Large'), ('NS', 'No specific')], default='NS', help_text="Base on international sizes. NS means 'no specific'.", max_length=4, verbose_name='Clothe size')),
                ('color', models.CharField(blank=True, help_text="User can choose the clothe's color.", max_length=16, verbose_name='Clothe color')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clothe category')),
                ('gender', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='NS', help_text='Genero preferido para la prenda.', max_length=9, verbose_name='Gender preferential for clothe.')),
                ('brand', models.CharField(blank=True, max_length=70, verbose_name='Clothe brand')),
                ('state', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], default='NS', help_text='Estado de la prenda.', max_length=7, verbose_name='Clothe state')),
                ('public', models.BooleanField(default=True, help_text='The user can choose when hide her/him clothe from catalog.', verbose_name='Clothe is public')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Clothe likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Clothe dislikes')),
                ('super_likes', models.PositiveIntegerField(default=0, verbose_name='Clothe Super-likes')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which object was last modified.', verbose_name='modified at')),
                ('value', models.CharField(choices=[('LIKE', 'like'), ('SUPERLIKE', 'superlike'), ('DISLIKE', 'dislike')], max_length=9, verbose_name='Interaction type')),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.ClothesModel')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
